name: Build and Deploy
on:
    push:
    
    pull_request:
        branches:
            - main
    
jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v5
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 22.22.x
                cache: npm
            - run: npm install
            - run: npm run mocha:test
            - run: npm run build
